# Generated by Django 5.1.2 on 2024-12-23 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_replyvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='replyvote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='replyvote',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='replyvote',
            name='user',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('question', 'Question'), ('reply', 'Reply')], max_length=10)),
                ('content_id', models.PositiveIntegerField()),
                ('vote_type', models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content_type', 'content_id')},
            },
        ),
        migrations.DeleteModel(
            name='QuestionVote',
        ),
        migrations.DeleteModel(
            name='ReplyVote',
        ),
    ]
