# Generated by Django 5.1.2 on 2024-11-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_bio_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pic/default.jpg', upload_to='profile_pic'),
        ),
    ]
